spring:
  application:
    name: trypto-backend
  datasource:
    url: jdbc:h2:mem:trypto;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        rewriteBatchedStatements: true
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

app:
  websocket:
    endpoint: /ws
    heartbeat-send: 10000
    heartbeat-receive: 10000
